version: '3'
services:
  db:
    image: mysql:5.7.31
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ezlink
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      # 防止中文乱码
      LANG: C.UTF-8
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    container_name: mysql_ezlink
    volumes:
      # 挂载 migration.sql 到 mysql 容器的初始化脚本中
      - ./migration.sql:/docker-entrypoint-initdb.d/migration.sql

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    container_name: redis_ezlink

  zookeeper:
    image: zookeeper:latest
    # 本地端口 2181 映射到容器端口 2181
    ports:
      - "2181:2181"
    container_name: zookeeper_ezlink

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka_ezlink
    # 等待zk启动后再启动
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      # kafka 集群中，每个 kafka 都有一个 BROKER_ID 来区分自己
      - KAFKA_BROKER_ID=0
      # 配置 zookeeper 管理 kafka 的路径
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper_ezlink:2181/kafka
      # 把kafka的地址端口注册到 zookeeper 上, 服务器部署需要把 localhost 换成服务器的 IP 地址
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      # kafka监听地址
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092

  dubbo:
    image: chenchuxin/dubbo-admin:latest
    container_name: dubbo_ezlink
    depends_on:
      - zookeeper
    ports:
      - "9090:8080"
    environment:
      - dubbo.registry.address=zookeeper://zookeeper_ezlink:2181
      - dubbo.admin.root.password=root
      - dubbo.admin.guest.password=guest
